### ISSUE TITLE
section numbering in Notes

### ISSUE THREAD

**Issue by abmantz** [LSSTDESC/desc-tex#13]
Some users would like sections in Notes to be numbered, especially when using a ToC. See [here](https://github.com/LSSTDESC/start_paper/issues/45) for a solution. However, ideally, we could make this an option to the class instead of something that requires modifying the class file.

**Comment by drphilmarshall** [comment]
The `lsstdescnote.cls` file now (after PR #18) has section numbering by default, which is the right thing I think: people expect to be able to cross-reference sections in latex docs and see "Section 12.3" etc appear in their PDF. I think this is OK to close out.
