### ISSUE TITLE
Winter 2018 hacks

### ISSUE THREAD

**Issue by abmantz** [LSSTDESC/desc-tex#17]
Please reply to this issue with wants/needs related to [`desc-tex`](https://github.com/LSSTDESC/desc-tex) **or** [`start_paper`](https://github.com/LSSTDESC/start_paper). You can see existing issues for these projects [here](https://github.com/LSSTDESC/desc-tex/issues) and [here](https://github.com/LSSTDESC/start_paper/issues).

Don't be afraid to repeat something that is already an issue; this list is intended to identify high priority things that we might be able to make progress on during the hack day.

Similarly, new requests identified here should still be issued in the usual way. Regardless, it would be nice to link to an Issue in replies below.

**Comment by drphilmarshall** [comment]
Yes! The pub board returns to Hack Day :-)

OK, near the top of my wishlist is a DESC Note explaining DESC Notes - why
they look the way they do, why we have so many formats, how to think about
them etc. Some of this would be explaining the pub policy, but there's some
other stuff that I wish I had written down ages ago. It'd be good to get
back to that. I was thinking the Notes Note could live in the start_paper
repo.
