### ISSUE TITLE
bibtex for LSST products (from [start paper](https://github.com/LSSTDESC/start_paper/issues/72))

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/desc-tex#19]
This continues the [issue in `start_paper`](https://github.com/LSSTDESC/start_paper/issues/72) (which I will close) here following advice from @abmantz of getting documents such as the LSST data products definition documents into the bibtex. As @drphilmarshall suggested in that issue, it might be good directly keep `lsstdesc.bibtex` for desc documents, and a separate bibtex file for project documents. Further, he points out that it is good to be able to use a project supplied bibtex rather than roll our own.  

So, looking into this, there seems to be:
- the [LSSTReferences repository and bibtex](https://github.com/lsst-pst/LSSTreferences/blob/master/LSSTbiblio.bib) that seems most suitable for this.
- From past rummages, I also recall [one being used in the overview paper](https://github.com/lsst-pst/overview_paper/blob/u/timj/bibtex/lsst.bib). Perhaps, we can find out from someone like @timj if the first one is the best for this?

**Comment by timj** [comment]
I don't necessarily agree with some of the LSSTReferences bibtex but I don't really follow it. Internally we use https://github.com/lsst/lsst-texmf/tree/master/texmf/bibtex/bib for shared bibtex entries. The overview paper is specifically the papers used by the overview paper and not meant to be a shared resource -- I automatically downloaded them from ADS based on the bibcodes).

**Comment by abmantz** [comment]
I'm wondering whether it's actually wise for us (DESC) to directly include a Project bib file in `desc-tex`. I assume we wouldn't be curating it, so all we could really do is periodically update bib files from one of the repos mentioned above. But, on the other hand, the user could always just do this themselves by downloading the files or `git submodule`ing (we could perhaps streamline that step). This would be a little convoluted, but still seems preferable to maintaining our own bib for the project. Any thoughts? (cc @drphilmarshall)

**Comment by rbiswas4** [comment]
Thanks @timj . @abmantz my 2c: I think this should provide these references rather than expect the user to download them. This is a way in which collaborative efforts once could help several users in writing documents and be a net gain.  But I agree that rather than periodically copying manually, automating this through `git submodule` is a better way to go. I don't think I know of the top of my head how to do that for a single file, but perhaps that is not necessary.

**Comment by timj** [comment]
you can't add a single file via git submodule, but you can add the module and also commit a softlink to the right place in the submodule.

**Comment by abmantz** [comment]
Ok... so maybe this was a `start_paper` issue after all. I think the natural solution would be to handle the Project repo there in the same way as `desc-tex`, i.e. for latex projects the Makefile will deal with setting up the submodule and including the appropriate path in the bibtex search. From the comments above, it seems that there are a few options, but that `lsst/lsst-texmf` is what we should use.
