### ISSUE TITLE
Solar and stellar unit formatting?

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/desc-tex#22]
Solar and stellar units [(i.e., \Msolar, \Mstar, \Lsolar, \Lstar, and associated aliases)](https://github.com/LSSTDESC/desc-tex/blob/4f8117f2fbd37a9f797422f6c6b75ba88694ec5e/styles/lsstdesc_macros.sty#L78-L83) are currently italicized. I think they probably shouldn't be, but I thought maybe @sethdigel or @abmantz might have a more definitive answer.

**Comment by abmantz** [comment]
This is a journal-dependent convention. I know that MNRAS wants them upright, whereas the couple of ApJ papers I checked out just now have \Msolar italicized. My guess is that ApJ is the most frequently used journal amongst DESCers, in which case it makes sense to leave it as is.

fwiw, I also think it makes more sense this way. The mass of the Sun is an imperfectly known variable, not a defined unit named after someone whose name begins with M.

**Comment by sethdigel** [comment]
I'm with MNRAS on this.  Distinguishing units from variables is worthwhile.  Also, the [DESC Style Guide](https://github.com/LSSTDESC/Style_Guide) is emphatic about  this point (and I don't _think_ that I wrote the words).

**Comment by abmantz** [comment]
Well, I obviously didn't write them, which just means we copied it over from Planck. And it doesn't explicitly mention solar units. I completely agree with the emphasis where meters and seconds are concerned. If we're trying to be consistent, the question is whether the mass of the sun is a variable or a unit. The answer is that it can be argued either way.

Given that our guide is only a guide, and is trumped by the journals we submit to, I personally think the most important consideration is the "most of us use journal X" one. This is *totally* independent of the fact that it supports my preference.

But anyway, if you really want, we can change it.

**Comment by sethdigel** [comment]
I guess I won't vote for overriding style acceptable to ApJ.

**Comment by abmantz** [comment]
Unless @kadrlica has strong feelings to add, I'll close this then.
