### ISSUE TITLE
LSST references

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/desc-tex#24]
From discussions with @abmantz and @drphilmarshall in https://github.com/LSSTDESC/start_paper/issues/72 

I believe this is the repository that is used through submodule to provide general references for DESC. I do obtain the `lsstdesc.bib` file. However, I am trying to refer to things that are cited [here](https://github.com/lsst-pst/LSSTreferences) for example the [MAF framework](https://github.com/lsst-pst/LSSTreferences/blob/master/LSSTbiblio.bib#L75). These are not included in the `lsstdesc.bib` yet. 

I could include them in the bib file and PR this repo. Or maybe there is a plan to include those files through some other sub-modulling (but this might be hard as the files there have some different conventions and repeats). Any suggestions?

**Comment by abmantz** [comment]
Our plan was to not try to replicate a bibliography for LSST Project references that already exists elsewhere, just to provide one for DESC specifically. So unless I misunderstand the nature of the references you're looking for, they should not be added to `desc-tex`. Why not just copy/submodule the `LSSTreferences` bibliography? (Though I had been under the impression that it would be retired in favor of some other Project bibliography.)

**Comment by rbiswas4** [comment]
Thanks!  

The problem is that ` LSSTreferences` will not work out of the box with `desc-tex`, partly due to duplicate references.  Maybe this should be left till the project bibliography builds up?

**Comment by abmantz** [comment]
I see; I hadn't realized that the original `desc-tex` bib included Project things, but it clearly does now that I look. I guess we should remove those to avoid duplication. What are the other issues that prevent them from working together?

**Comment by rbiswas4** [comment]
I was not sure, but now that I know the plan, I am happy to try  checking this out ...and report back by simply copying the `LSSTReference.bib` and changing my `lsstdesc.bib`

It would of course be interesting to know if this has already been retired.

**Comment by abmantz** [comment]
Thanks, that would be helpful.

I'm not sure what you meant by "retired" though. We don't plan on retiring the desc-tex bibliography unless it unexpectedly turns out not to be useful to anyone, but it seems a little early to judge that.

**Comment by rbiswas4** [comment]
> I'm not sure what you meant by "retired" though. We don't plan on retiring the desc-tex bibliography unless it unexpectedly turns out not to be useful to anyone, but it seems a little early to judge that.

This was about `LSSTReferences.bib` which you mentioned was being retired in favor of something newer (not `desc-tex`). In this case it would make sense to copy the newer one rather than than `LSSTReferences.bib`

**Comment by rbiswas4** [comment]
Sounds good!
