### ISSUE TITLE
A&A template?

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/desc-tex#33]
Are there plans to support the A&A format for docswitch?  If not, @cavestruz and I would like to formally request that.  Thanks!

**Comment by kadrlica** [comment]
Since docswitch is deprecated, I'm closing this issue. There is an issue to deal with A&A author formatting in [mkauthlist #17](https://github.com/DarkEnergySurvey/mkauthlist/issues/17), but it looks like it is not a trivial change.
